##start with a base image
#FROM openjdk:21-jdk-slim
#
##information around who maintain the image
#MAINTAINER imecreative
#
##Add the application's jar to the container
#COPY target/course-service-0.0.1-SNAPSHOT.jar course-service-0.0.1-SNAPSHOT.jar
#
##Excecute the application
#ENTRYPOINT ["java","-jar","/course-service-0.0.1-SNAPSHOT.jar"]
#
#
